#!/bin/bash

# yay
sudo pacman -Syu --needed git base-devel && git clone https://aur.archlinux.org/yay-bin.git && cd yay-bin && makepkg -si

yay -Syu --noconfirm \
  hyprland waybar hyprlock hypridle hyprpaper wl-clipboard pavucontrol clipse sddm wl-clip-persist walker-bin hyprland-per-window-layout mako qt5-wayland qt6-wayland noto-fonts noto-fonts-extra noto-fonts-emoji woff2-font-awesome xdg-desktop-portal-gtk xdg-desktop-portal-hyprland plymouth plymouth-theme-catppuccin-mocha uwsm hyprpicker\
  gnome-calculator gnome-weather fontconfig gnome-keyring gnome-themes-extra noto-fonts-cjk noto-fonts-emoji noto-fonts-extra yaru-icon-theme libqalculate sushi\
  \
  swappy hyprshot wl-screenrec wf-recorder slurp \
  \
  alacritty ghostty nautilus nextcloud-client fzf starship fd man stow tmux fzf-tmux rip-grep bc unzip usbutils gum zip smbclient	gvfs-smb postgresql-libs git-delta wget\
  \
  firefox chromium thunderbird \
  \
  bitwarden 1password-cli 1password-beta \
  \
  neovim mise lazygit docker docker-compose ttf-jetbrains-mono-nerd stylua arduino-cli lazydocker imagemagick github-cli clang ansible-core \
  \
  mpv youtube-music vlc imv vlc-plugin-gstreamer vlc-plugin-ffmpeg\
  \
  discord telegram-desktop slack-desktop-wayland zoom\
  \
  neofetch btop gnome-disk-utility openvpn \
  \
  dbeaver \
  \
  freecad libreoffice bambustudio-bin prusa-slicer \
  \
  pipewire pipewire-pulse pipewire-jack wireplumber
  
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
mkdir -p ~/.config/tmux/plugins/catppuccin
git clone -b v2.1.3 https://github.com/catppuccin/tmux.git ~/.config/tmux/plugins/catppuccin/tmux

# Open all images with imv
xdg-mime default imv.desktop image/png
xdg-mime default imv.desktop image/jpeg
xdg-mime default imv.desktop image/gif
xdg-mime default imv.desktop image/webp
xdg-mime default imv.desktop image/bmp
xdg-mime default imv.desktop image/tiff

# Open PDFs with the Document Viewer
xdg-mime default org.gnome.Evince.desktop application/pdf

# Use Chromium as the default browser
xdg-settings set default-web-browser chromium.desktop
xdg-mime default chromium.desktop x-scheme-handler/http
xdg-mime default chromium.desktop x-scheme-handler/https

# Open video files with mpv
xdg-mime default mpv.desktop video/mp4
xdg-mime default mpv.desktop video/x-msvideo
xdg-mime default mpv.desktop video/x-matroska
xdg-mime default mpv.desktop video/x-flv
xdg-mime default mpv.desktop video/x-ms-wmv
xdg-mime default mpv.desktop video/mpeg
xdg-mime default mpv.desktop video/ogg
xdg-mime default mpv.desktop video/webm
xdg-mime default mpv.desktop video/quicktime
xdg-mime default mpv.desktop video/3gpp
xdg-mime default mpv.desktop video/3gpp2
xdg-mime default mpv.desktop video/x-ms-asf
xdg-mime default mpv.desktop video/x-ogm+ogg
xdg-mime default mpv.desktop video/x-theora+ogg
xdg-mime default mpv.desktop application/ogg

mise settings add idiomatic_version_file_enable_tools ruby

# Increase lockout limit to 10 and decrease timeout to 2 minutes
sudo sed -i 's|^\(auth\s\+required\s\+pam_faillock.so\)\s\+preauth.*$|\1 preauth silent deny=10 unlock_time=120|' "/etc/pam.d/system-auth"
sudo sed -i 's|^\(auth\s\+\[default=die\]\s\+pam_faillock.so\)\s\+authfail.*$|\1 authfail deny=10 unlock_time=120|' "/etc/pam.d/system-auth"

# Configure Docker daemon:
# - limit log size to avoid running out of disk
# - use host's DNS resolver
sudo mkdir -p /etc/docker
sudo tee /etc/docker/daemon.json >/dev/null <<'EOF'
{
    "log-driver": "json-file",
    "log-opts": { "max-size": "10m", "max-file": "5" },
    "dns": ["172.17.0.1"],
    "bip": "172.17.0.1/16"
}
EOF

# Expose systemd-resolved to our Docker network
sudo mkdir -p /etc/systemd/resolved.conf.d
echo -e '[Resolve]\nDNSStubListenerExtra=172.17.0.1' | sudo tee /etc/systemd/resolved.conf.d/20-docker-dns.conf >/dev/null
sudo systemctl restart systemd-resolved

# Start Docker automatically
sudo systemctl enable docker

# Give this user privileged Docker access
sudo usermod -aG docker ${USER}
sudo usermod -aG dialout ${USER}
sudo usermod -aG uucp ${USER}

# Prevent Docker from preventing boot for network-online.target
sudo mkdir -p /etc/systemd/system/docker.service.d
sudo tee /etc/systemd/system/docker.service.d/no-block-boot.conf <<'EOF'
[Unit]
DefaultDependencies=no
EOF

sudo systemctl daemon-reload

gsettings set org.gnome.desktop.interface gtk-theme "Adwaita-dark"
gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
gsettings set org.gnome.desktop.interface icon-theme "Yaru-blue"

# Set links for Nautilius action icons
sudo ln -snf /usr/share/icons/Adwaita/symbolic/actions/go-previous-symbolic.svg /usr/share/icons/Yaru/scalable/actions/go-previous-symbolic.svg
sudo ln -snf /usr/share/icons/Adwaita/symbolic/actions/go-next-symbolic.svg /usr/share/icons/Yaru/scalable/actions/go-next-symbolic.svg
sudo gtk-update-icon-cache /usr/share/icons/Yaru

# Ensure iwd service will be started
sudo systemctl enable iwd.service

# Prevent systemd-networkd-wait-online timeout on boot
sudo systemctl disable systemd-networkd-wait-online.service
sudo systemctl mask systemd-networkd-wait-online.service

dot-bin/sync-dotfiles

bat cache --build

# Autologin
sudo plymouth-set-default-theme -R catppuccin-mocha

sudo mkdir /etc/systemd/system/getty@tty1.service.d

sudo tee /boot/loader/loader.conf << 'EOF'
timeout 0
EOF

sudo tee /etc/systemd/system/getty@tty1.service.d/autologin.conf <<  'EOF'
[Service]
ExecStart=
ExecStart=-/usr/bin/agetty -o '-p -f -- \\u' --skip-login --noclear --nonewline --autologin yuri --noclear %I $TERM
EOF

# Then add quiet splash to the kernel parameters in /boot/loader/entries/<linux-date>.conf
