#!/bin/bash

set -euo pipefail

FILE="/tmp/last_checked_time"

last_iso=$(cat "$FILE")

repo="$1"

prs=$(gh pr list --repo "$repo" --search "user-review-requested:@me" --state open --json number,title,url,updatedAt)

mapfile -t pr_lines < <(echo "$prs" | jq -c '.[]')

for pr_json in "${pr_lines[@]}"; do
  date=$(jq -r .updatedAt <<< "$pr_json")
  title=$(jq -r .title <<< "$pr_json")
  
  input_ts=$(date -u -d "$date" +%s)

  last_ts=$(date -u -d "$last_iso" +%s)

  diff=$((last_ts - input_ts))
  echo "Time difference for '$title': $diff seconds"
  
  if [ "$diff" -lt 0 ]; then
    notify-send "New PR Review Request" "$title" --icon "$HOME/scripts/assets/gh.svg"
  fi
done

now_iso=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
echo "$now_iso" > "$FILE"
