#!/bin/sh

# Get the volume level and convert it to a percentage
volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@)
muted=$(echo "$volume" | awk -F'[][]' '{print $2}')

if [ "$muted" = "MUTED" ]; then
  notify-send -t 1000 -a 'wp-vol' "🔇"
else
  volume=$(echo "$volume" | awk '{print $2}')
  volume=$(echo "( $volume * 100 ) / 1" | bc)
  notify-send -t 1000 -a 'wp-vol' -h int:value:$volume "🔈 ${volume}%"
fi

